### ISSUE TITLE
Schemaparser performs schema update before CDN updates to the latest contents

### ISSUE THREAD

**Issue by maxlivinci** [MurmurationsNetwork/MurmurationsServices#104]
Solution:

1. If `last_commit` is the same as `schemas:lastCommit` we do nothing.

2. When `last_commit` minus `schemas:lastCommit` is smaller than 180s (3 minutes), we update schemes. Until it's greater than 3 minutes, we update `schemas:lastCommit`.

**Comment by geoffturk** [comment]
@maxlivinci Please put some logging in for what happens in step 2 so we can monitor it.

**Comment by maxlivinci** [comment]
closed by #106
