### ISSUE TITLE
Federated Murmurations with ActivityPub

### ISSUE THREAD

**Issue by aschrijver** [MurmurationsNetwork/MurmurationsServices#128]
I am posting here, because your website's contact form gives me an _"There was an error trying to send your message. Please try again later."_ error (Firefox, Ubuntu). Copying text:

---

I really like the Murmurations protocol, and it has great potential.

Just now I posted a topic to the [SocialHub community](https://socialhub.activitypub.rocks) - the group of technologists that innovate the Fediverse and ActivityPub-related open standards - with an implementation idea (a Murmurations Profile to track Interoperability support in federated apps).

But there exists a Fediverse application for Murmurations itself, and that comes in the form of federating the Murmurations Index, so that self-hosted index servers auto-synchronize with each other over the Fediverse (e.g. with the profiles they subscribe to).

If you are interested in that idea, then I invite you to hop onto our forum and discuss.

The thread just posted by me is: https://socialhub.activitypub.rocks/t/improvement-to-federation-md-convention-murmurations/1573

**Comment by geoffturk** [comment]
Hi. Thanks for reaching out to us. I forwarded your message to @olisb who will follow up with you guys next week (he's offline most of this week).

**Comment by matslats** [comment]
Hi thanks for thinking this through.
Are you clear about the difference between an index and an aggregator?
The murmurations protocol is all about the index but all the info is accessed via the aggregator, which has a slightly different API for each schema (different filter options anyway)
So the next step of clarity would involve:
- What it means to federate an index vs federating an aggregator.
- How the existing (index API) would be affected, or whether an index would have to run 2 APIs
- Whether it's worth building some kind of bridge from the fediverse to murmurations as it is.

**Comment by aschrijver** [comment]
Hey there. Nice to see additional comments on the issue, thank you. What I've penned down thus far are mostly still showerthoughts on the idea, while it is in the fridge. In a federated scenario there may be some fundamental changes to how things currently work.
