### ISSUE TITLE
Remove whitespace before generating profileHash

### ISSUE THREAD

**Issue by geoffturk** [MurmurationsNetwork/MurmurationsServices#14]
@maxlivinci I think we should do this to avoid the scenario in the future where the profile data is exactly the same but the hashes are different purely because of whitespace differences. But let's talk it through before you implement it.

**Comment by maxlivinci** [comment]
[done](https://github.com/MurmurationsNetwork/MurmurationsServices/commit/585ee3a4e45fbbfd4afa8f8e3503b117589ad22f)
