### ISSUE TITLE
[POST/nodes] Use schemaName instead of URLs

### ISSUE THREAD

**Issue by maxlivinci** [MurmurationsNetwork/MurmurationsServices#15]
Right now we are using a URL to link to each schema, but once we have the library service, it should only be a schemaName, not a full URL.

So right now we have: https://raw.githubusercontent.com/MurmurationsNetwork/MurmurationsLibrary/master/schemas/demo-v1.json

But with the library service, it will just be: demo-v1

The idea here is to not have a URL and thus eliminate a single point of failure (i.e., GitHub) since these schemas and fields will be distributed across multiple libraries.

It will be the responsibility of the maintainers of the library repo on GitHub to ensure that all new schemas have a unique name and do not overwrite a previous schema by using the same name.

**Comment by olisb** [comment]
I get the idea of eliminating the single point of failure - but shouldn't there be some reference to a repository / Library somewhere? ... otherwise anyone stumbling across a map / directory and poking into the code may not be able to find out where to find out more...

**Comment by geoffturk** [comment]
The library will be referenced as part of the protocol. Finding it randomly in a profile on a node is not where it will be discovered.
