### ISSUE TITLE
schemas with semver versions in the name are currently disallowed

### ISSUE THREAD

**Issue by wu-lee** [MurmurationsNetwork/MurmurationsServices#150]
The latest schema I submitted via https://github.com/MurmurationsNetwork/MurmurationsLibrary/pull/34 cannot yet be used, because the default-v1 schema asserts that schema names can only contain alphanumeric characters, hyphens and underscores:

    curl --header "Accept: application/json" https://index.murmurations.network/v1/nodes/9d559f8a862e6067753a901027278beb9c4054dde65263971e2d94f4c27262ca

Returns:

    {
      "data":{
        "node_id":"9d559f8a862e6067753a901027278beb9c4054dde65263971e2d94f4c27262ca",
        "profile_url":"https://dev.lod.coop/sea-lod/oxford/65.murm.json",
        "status":"validation_failed",
        "failure_reasons":[
          "default-v1.linked_schemas.0: Does not match pattern '[A-Za-z0-9-_]{4,100}$'"
        ]
      }
    }

I think the intent is to expand this to allow periods, and therefore semantic version numbers like `0.1.0`?

(Also, there seems to be no anchor at the start of the regex, not sure if this implicit?)

**Comment by olisb** [comment]
I've added period to the allowed pattern, but someone else will need to review the change before it can be merged
