### ISSUE TITLE
Registration with outcome response in one step

### ISSUE THREAD

**Issue by wu-lee** [MurmurationsNetwork/MurmurationsServices#152]
Currently it seems like to register a profile, and ensure that it worked, you need to:

1. Register by POSTing the profile's URL to `https://index.murmurations.network/v1/nodes`
2. Check whether that succeeded by GETiing the node status page at `https://index.murmurations.network/v1/nodes/<NODE ID>`

Step two is needed because step one does not indicate success or failure to validate the profile. It returns 200 OK in either case, and there is no indication in the response body, either.

Would it be possible to include the information obtained in step 2 in step 1?  This would simplify the process of registration to one step.

(I am currently coding a bulk registration script for SEA profiles, so will need to execute the two-step process for now, but this seems like a useful improvement for the future.)

**Comment by geoffturk** [comment]
Consider setting up a service that takes a profile registration request and replies with confirmation/error once the node's `profile_url` is processed by the index. This will enable promise-based submissions.
