### ISSUE TITLE
Index should not return 404 status when no nodes match query parameters

### ISSUE THREAD

**Issue by Photosynthesis** [MurmurationsNetwork/MurmurationsServices#174]
Current behaviour of the index is that if query parameters are set on the request, and no nodes exist that match the query (eg https://index.murmurations.network/v1/nodes?schema=systems_change_map-v1&country=CA), the index returns a 404 status code. 

This is problematic because clients handling the response have to deal with the ambiguity of an "error" status code when in fact the request was successful. For example, a cURL request will treat this as an error, and cURL's built-in error handling would have to be worked against to handle non-error 404s correctly. 

Using a 404 for no search results is not required by REST standards (since there is not a specific missing resource) and is recommended against in this sort of use case. (See for example https://softwareengineering.stackexchange.com/questions/358243/should-no-results-be-an-error-in-a-restful-response)

**Comment by geoffturk** [comment]
Changes to make:

1) Return `200` status code instead of `404` in HTTP headers

2) Only return the `message` parameter in the body object; remove the `status` parameter. Example:

```json
{
    "message": "Could not find node_id: 51d677359e6e55f6bd22fe53cb694ffb4506f89df3ea022794b999cae6387045"
}
```

Or:

```json
{
    "message": "No items found matching given criteria."
}
```
