### ISSUE TITLE
Investigate GitHub Action deployment errors

### ISSUE THREAD

**Issue by geoffturk** [MurmurationsNetwork/MurmurationsServices#192]
https://github.com/MurmurationsNetwork/MurmurationsServices/actions

https://github.com/MurmurationsNetwork/MurmurationsServices/runs/4663814190?check_suite_focus=true

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/32190662/147871957-b0ddb382-4455-4008-833a-a31eb75ec5ea.png">

**Comment by TingSyuanWang** [comment]
@geoffturk @maxsarratt We can check the url in the below.

https://stackoverflow.com/questions/67520866/no-matches-for-kind-cronjob-in-version-batch-v1

Our test environment kubernetes should upgrade to higher than 1.19's version.

**Comment by TingSyuanWang** [comment]
@geoffturk Hi, I think the Github Action works perfectly now. Please review it.
