### ISSUE TITLE
Upgrade mongoDB & document upgrade steps for volume management

### ISSUE THREAD

**Issue by TingSyuanWang** [MurmurationsNetwork/MurmurationsServices#221]
Upgrade MongoDB to 4.4.11 using `helm upgrade` failed, because the new pod created and tried to mount the old pod's storage. However the storage can't be mounted by two pods. Here, we need to think about how to destroy the pod first then create a new MongoDB pod to mount the old storage.

Also, the latest version is 5.0.5, we need to dig how to upgrade from 4.4 to 5.0.
(https://docs.mongodb.com/manual/release-notes/5.0-upgrade-replica-set/)

**Comment by TingSyuanWang** [comment]
Set accessModes as ReadWriteMany can make the roll update working.
```
accessModes:
  - ReadWriteMany
 ```

**Comment by geoffturk** [comment]
Resolved by #239
