### ISSUE TITLE
Do we need to store `validated` status for a node?

### ISSUE THREAD

**Issue by maxlivinci** [MurmurationsNetwork/MurmurationsServices#27]
Once we know that the node is valid, we will immediately parse into ES.

So the status for a valid node is either `posted` or `posted_fail`.

My question is that do we need to store `validated` status for a node?

**Comment by geoffturk** [comment]
If ES fails, what status would it be in then? `received`?

I think it is worth keeping the `received` status, even if that status will usually only be for a very brief amount of time. The definition of `posted` may change in the future such that there may be a longer amount of time between `validated` and `posted` status.

**Comment by maxlivinci** [comment]
> If ES fails, what status would it be in then? received?

posted_fail

**Comment by maxlivinci** [comment]
> I think it is worth keeping the `received` status.

Do you mean `validated`?

**Comment by geoffturk** [comment]
Sorry, yes, I meant `validated`.

**Comment by maxlivinci** [comment]
> The definition of `posted` may change in the future such that there may be a longer amount of time between validated and posted status.

Agree. Close this issue.
