### ISSUE TITLE
Profile instance not being validated against default schema

### ISSUE THREAD

**Issue by geoffturk** [MurmurationsNetwork/MurmurationsServices#288]
New profiles submitted to the index should be validated against the default schema (currently `default-v2.0.0`) before being validated against the list of `linked_schemas` but this is not currently happening.

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/32190662/163362814-e9856eff-0873-427e-8b50-fd9b1324d5ef.png">

Currently it only happens when the default schema is specified in the `linked_schemas` array, but this is not correct behavior.

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/32190662/163362893-f8d45e6e-74fc-4ec8-8b77-5e274da34030.png">

**Comment by TingSyuanWang** [comment]
Resolves #289
