### ISSUE TITLE
Only delete profile if it no longer exists at node's profileUrl

### ISSUE THREAD

**Issue by geoffturk** [MurmurationsNetwork/MurmurationsServices#29]
The node operator first needs to remove the profile from the profileUrl (it should return a 404) before the profile is removed from the index.

**Comment by geoffturk** [comment]
@maxlivinci When you implement this, we should have a dev environment override so we don't actually have to delete the profiles from the `profile_url`s when we are testing. It should be configurable so we can test with the delete requirement on if we want, but normally in dev mode it will be off.

**Comment by geoffturk** [comment]
Also, I am still not convinced always returning `200 OK` is the right thing here. There are two scenarios where there should be an error message:

1) Profile does not exist in the index
2) Profile is still available at its URL on the node's website

We don't want to "leak" information by informing the user that #2 is the issue, so I suggest we just return a `404 Not Found` error in the case of both 1 & 2 above. `200 OK` will only be returned if an existing profile is removed from the index (assuming it is no longer accessible at its `profile_url`).

**Comment by maxlivinci** [comment]
> We don't want to "leak" information by informing the user that #2 is the issue, so I suggest we just return a 404 Not Found error in the case of both 1 & 2 above. 

If you return 404 Not Found then people know the internal implementation.

If you DELETE something that doesn't exist, you should just return a 204 (even if the resource never existed). The client wanted the resource gone and it is gone. Returning a 404 is exposing internal processing that is unimportant to the client and will result in an unnecessary error condition.

**Comment by maxlivinci** [comment]
ref: 

- https://jsonapi.org/format/#crud-updating-to-many-relationships
- https://jsonapi.org/format/#crud-deleting

**Comment by geoffturk** [comment]
As discussed, there's no need to worry about the "leak" scenario. Let's go with 404/400 for cases 1/2 above. Thanks.
