### ISSUE TITLE
Check for and process profile postings stuck in the state transition flow

### ISSUE THREAD

**Issue by geoffturk** [MurmurationsNetwork/MurmurationsServices#46]
**Handle `post_failed` events after ES recovery**

When Elasticsearch is down, any new node profiles will be put into `post_failed` status. There should be some recovery procedure that checks for these failure events and attempts to repost them to ES when it is back online.

**Comment by geoffturk** [comment]
**Handle events stuck in `received` state**

There was an issue with the index or validation service recently where a few profiles were stuck with `received` status. Ideally they should be moved further through the state transition flow to `posted` status as soon as everything is back online working correctly again.

![image](https://user-images.githubusercontent.com/32190662/104443711-107d4580-5597-11eb-84e0-35d36fcbb856.png)

**Comment by maxlivinci** [comment]
closed this in #95
