### ISSUE TITLE
Remove schema `version` field from Library DB

### ISSUE THREAD

**Issue by geoffturk** [MurmurationsNetwork/MurmurationsServices#472]
The version is already recorded in the schema name so no need for this redundant field.

<img width="279" alt="image" src="https://github.com/MurmurationsNetwork/MurmurationsServices/assets/32190662/aa879a0d-93fe-43e9-8830-4c50f04d456b">

Code change:

<img width="1286" alt="image" src="https://github.com/MurmurationsNetwork/MurmurationsServices/assets/32190662/0ba1c76f-aab3-4de8-8baf-7c9c152d7370">

**Comment by geoffturk** [comment]
Just check to make sure we don't use this version field anywhere else in the code base, and if not, then go ahead and delete the field from the schemas that still have it (in test and prod mongodb).

**Comment by TingSyuanWang** [comment]
After confirming, it has been determined that the "version" field is no longer utilized in the codebase and can be safely removed. As the result, I have deleted the "version" field in the test env. It is worth noting that the prod env does not possess this field and thus no deletion is required.
