### ISSUE TITLE
Move the primary URL validation into the validation service

### ISSUE THREAD

**Issue by maxsarratt** [MurmurationsNetwork/MurmurationsServices#540]
- Put the primary URL validation into the validation service 
- If it fails validation by the URI processor, we want to return a 400 error with the reason for failure.

**Comment by geoffturk** [comment]
We'll probably want to set it to `validation_failed` status if there is any kind of problem during the validation step. If the problem occurs after the profile is validated, we probably want to set it to `post_failed`. Ideally we avoid creating a new status type.

**Comment by geoffturk** [comment]
Related to #539

**Comment by maxsarratt** [comment]
@geoffturk If we set the status to post_failed, the revalidation node service will send it to revalidation, causing it to enter an infinite loop: https://github.com/MurmurationsNetwork/MurmurationsServices/blob/main/services/cronjob/revalidatenode/internal/service/node.go#L27-L31

**Comment by geoffturk** [comment]
Yes, makes for sense to put it in the validation service. 👍

If it fails validation by the URI processor, we want to return a 400 error with the reason for failure.
