### ISSUE TITLE
Strip out the non-indexed fields before passing the JSON instance to ES for processing

### ISSUE THREAD

**Issue by maxsarratt** [MurmurationsNetwork/MurmurationsServices#558]
When I wrote [tests](https://github.com/MurmurationsNetwork/MurmurationsServices/pull/557/files#diff-f198d179caabce55f90e9323c320240d691f7b151b7995ba8ad510cffd8b50a4R212) for the schemavalidator, I noticed that when I provide unspecified data, it can pass the validation. I think we should not allow users to add random data, and we can prevent this by adding the [additionalProperties](https://json-schema.org/understanding-json-schema/reference/object.html#additional-properties): false attribute to the schema definition.

```
--- FAIL: TestValidate (0.01s)
    --- FAIL: TestValidate/Profile_with_Unspecified_Data (0.00s)
        /Users/max/Desktop/MurmurationsServices/pkg/schemavalidator/schemavalidator_test.go:289: 
            	Error Trace:	/Users/max/Desktop/MurmurationsServices/pkg/schemavalidator/schemavalidator_test.go:289
            	Error:      	Not equal: 
            	            	expected: false
            	            	actual  : true
            	Test:       	TestValidate/Profile_with_Unspecified_Data
FAIL
FAIL	github.com/MurmurationsNetwork/MurmurationsServices/pkg/schemavalidator	0.378s
```

**Comment by geoffturk** [comment]
There are cases where it may be useful to add additional data beyond what is specified in the schema, so we have avoided restricting additional properties. As long as it is valid JSON (which the JSON parser should be verifying), it is OK to have other properties in the instance of the schema beyond those defined by it.

**Comment by maxsarratt** [comment]
If users can add random fields, then we probably need to define several principles. For example, how deep a JSON can be nested, how large a field can be, and what the total size of the JSON can be. Otherwise, people have many ways to crash our system.
