### ISSUE TITLE
Set revisionHistoryLimit to Delete Old Replicasets

### ISSUE THREAD

**Issue by TingSyuanWang** [MurmurationsNetwork/MurmurationsServices#566]
## Issue Description

When running `kubectl get rs -A -o wide`, I've noticed that old replicasets are still present, which makes us difficult to manage resources effectively.

## Proposed Solution

1. I propose that we update the deployment charts to include a `revisionHistoryLimit` value. This parameter will limit the number of revisions stored for a deployment, thus preventing older replicasets from being visible when using `kubectl get rs`.

2. Add a `revisionHistoryLimit` field within the deployment specification and set an appropriate value. For example:
   ```yaml
   spec:
     revisionHistoryLimit: 0 // Set as 0 to remove all historical replicasets.
     ```

## Potential unsolved problem

I've noticed that we have outdated replicasets for Velero and kube-system. We can manually execute the command `kubectl delete rs -n` to remove them, but this is not a permanent solution.

## Ref
1. https://wildwolf.name/how-to-delete-old-replicasets-in-kubernetes/

**Comment by maxsarratt** [comment]
Thanks for identifying the issue. 👍

**Comment by geoffturk** [comment]
<img width="1158" alt="image" src="https://github.com/MurmurationsNetwork/MurmurationsServices/assets/32190662/24dd5440-2656-48ce-a2c4-cbc431e90ff1">

The above deployments were still hanging around after the merged PR cleared out the old ReplicaSets for the other services.

Can we add a `revisionHistoryLimit` for these as well? If so, where?

**Comment by maxsarratt** [comment]
- `cilium-operator` (responsible for networking and network policies) and `coredns` (the DNS server for Kubernetes) are fundamental components within the Kubernetes ecosystem. It's advisable to retain their current configurations.

- I couldn't locate any information or YAML files related to [murmurations/goatcounter](https://hub.docker.com/r/murmurations/goatcounter) and [murmurations/allocator](https://hub.docker.com/r/murmurations/allocator) in our repository.

- `velero` is associated with backup processes. I'll review our documentation and draft a YAML file for it.

**Comment by geoffturk** [comment]
> I couldn't locate any information or YAML files related to [murmurations/goatcounter](https://hub.docker.com/r/murmurations/goatcounter) and [murmurations/allocator](https://hub.docker.com/r/murmurations/allocator) in our repository.

@TingSyuanWang can you update the manifests for these two so they clean up after themselves as well? Thanks.

**Comment by TingSyuanWang** [comment]
> > I couldn't locate any information or YAML files related to [murmurations/goatcounter](https://hub.docker.com/r/murmurations/goatcounter) and [murmurations/allocator](https://hub.docker.com/r/murmurations/allocator) in our repository.
> 
> @TingSyuanWang can you update the manifests for these two so they clean up after themselves as well? Thanks.

No problem!
