### ISSUE TITLE
Parsing Issue with "$ref" in Schema

### ISSUE THREAD

**Issue by TingSyuanWang** [MurmurationsNetwork/MurmurationsServices#571]
## Bug Description

We have encountered a parsing issue with schemas containing the "$ref" keyword in the schemaparser cronjob. The schema didn't parse "$ref": "../fields/xxx.json" into the schema.
Half an year ago, our frontend relies on a parsing library that is no longer maintained. To address this issue, we made modifications to the library and schemaparser services to ensure correct schema parsing. However, we have noticed that the "$ref" keyword is not being parsed correctly right now.

## Bug Details

The issue can be demonstrated by comparing schemas in production and test environments:

1. Production Schema (Working as Expected):
URL: [Production Schema](https://library.murmurations.network/v2/schemas/karte_von_morgen-v1.0.0)
This schema does not contain "$ref" and parses correctly.

2. Test Schema (Problematic):
URL: [Test Schema](https://test-library.murmurations.network/v2/schemas/karte_von_morgen-v1.0.0)
The schema in the test environment contains "$ref," which is not parsed correctly.

## Code Reference

The code responsible for parsing the schema is located at the following GitHub repository and line number:
[Link to Code](https://github.com/MurmurationsNetwork/MurmurationsServices/blob/2d601a875bf887636eca7f0fc4431187eb92f76a/services/cronjob/schemaparser/internal/service/schema_service.go#L139)

We use the following code snippet for parsing JSON parts:
```
parsedFullData := s.parseProperties(fullData)
```

It appears that this code has been removed from the main branch. You can use it as a reference, and please feel free to make any improvements.

## Desired Outcome

We need the parsing schemas from MurmurationsLibrary repo to correctly handle schemas containing the "$ref" keyword, as demonstrated in the production schema. The library should be able to resolve and parse the referenced schema as expected.

**Comment by maxsarratt** [comment]
We do have the parseProperties function available at [this link](https://github.com/MurmurationsNetwork/MurmurationsServices/blob/main/services/cronjob/schemaparser/internal/schemaparser/parser.go#L146-L187). However, it's not working for some reason.

**Comment by TingSyuanWang** [comment]
> We do have the parseProperties function available at [here](https://github.com/MurmurationsNetwork/MurmurationsServices/blob/main/services/cronjob/schemaparser/internal/schemaparser/parser.go#L146-L187). However, it's not working for some reason.

@maxsarratt Thanks for the update. Let me check from my side here. Once I've completed the changes, I'll create a PR.

**Comment by maxsarratt** [comment]
Close this PR because the underlying issue stemmed from a mistake in the schema structure; the "required" was placed in the wrong section, leading to parsing errors in Go. resolved by https://github.com/MurmurationsNetwork/MurmurationsLibrary/pull/109
