### ISSUE TITLE
feat: check if the profile hash is the same before updating index

### ISSUE THREAD

**Issue by maxyzli** [MurmurationsNetwork/MurmurationsServices#614]
In #612, we decided to remove the hash check from the index service and move it to the validation service.

The issue arises from our use of a microservice architecture, which typically means that direct connections to different services' databases should be avoided; doing so could undermine the fundamental reasons for adopting a microservice approach in the first place.

---

## Possible Solutions

- Event-Driven Architecture
- Data Replication
- Service-to-Service Communication

**Comment by geoffturk** [comment]
1)  The index service receives a potentially updated profile
2) The profile is immediately validated by the validation service
  a) If it is not valid, send the validation errors back to the requester
  b) If it is valid:
3) The validation service generates the profile_hash based on the relevant fields from the linked_schemas for the profile
4) The index service checks to see if the profile_hash is the same as the previous version for that profile
  a) If yes, just ignore it - do not change last_updated
  b) If no, update the relevant fields in the index (if any of the changed fields happen to be indexed in the index) and update the last_updated timestamp for the profile
