### ISSUE TITLE
Enrich Logs with Kubernetes Metadata

### ISSUE THREAD

**Issue by maxyzli** [MurmurationsNetwork/MurmurationsServices#705]

**Comment by maxyzli** [comment]
@geoffturk  After numerous attempts, there are no more errors in Fluentd, but the logs still aren’t showing up. I’m not sure what exactly is causing the issue.

**Comment by geoffturk** [comment]
@maxyzli OK, it's not a high priority so let's park it for now in the backlog so you can focus on #786 instead. Thanks for your efforts.
