### ISSUE TITLE
Migrate MongoDB from DigitalOcean to Contabo

### ISSUE THREAD

**Issue by maxyzli** [MurmurationsNetwork/MurmurationsServices#745]
## Research

- [x] How To expose a self-hosted MongoDB database for external use?

**Comment by vthwang** [comment]
Affected Services:

- [ ] Allocator
- [ ] Synchronizer (Vercel Part)
- [ ] Tools

**Comment by vthwang** [comment]
# How to update the PR.

## Stop service and backup MongoDB

- [ ] Update Variables to prevent write data into MongoDB
  - [ ]  Tools
  - [ ]  Synchronizer (Vercel)
- [ ] Backup MongoDB
- [ ] Restore MongoDB to new Mongo

## 1. Tools

- [ ] Merge the PR.
- [ ] Don't forget to deploy to test branch.

## 2. Synchronizer

- [ ] Merge the PR.
- [ ] Don't forget to deploy to test branch.

## 3. Allocator

- [ ] Update Secrets
- [ ] Merge the PR.
- [ ] Check the GitHub Action Deployment.

**Comment by vthwang** [comment]
Done.
