### ISSUE TITLE
Stress test Index API to get load metrics

### ISSUE THREAD

**Issue by geoffturk** [MurmurationsNetwork/MurmurationsServices#780]
https://k6.io/

Use a tool like k6 to stress test the Index API and get metrics for the amount of reads and writes the index can handle based on the spec of the k8s cluster it is running on.

**Comment by maxyzli** [comment]
# How to Perform Load Testing

## 1. Update the Hosts

```bash
echo -e "\n142.132.160.156 load-testing-index.murmurations.network\n142.132.160.156 load-testing-library.murmurations.network\n142.132.160.156 load-testing-data-proxy.murmurations.network" | sudo tee -a /etc/hosts
```

## 2. Install k6

```bash
brew install k6
```

## 3. Write a Script

- We will use the constant-arrival-rate executor for load testing. Adjust the rate to increase the requests per second.
- Virtual users can be thought of as the number of threads to execute the function. If the rate is greater than the maxVUs, then you won't be able to hit the desired rate.

```javascript
import http from 'k6/http';
import { check } from 'k6';

export let options = {
  scenarios: {
    constant_request_rate: {
      executor: 'constant-arrival-rate',
      rate: 100, // Number of requests per second
      timeUnit: '1s',
      duration: '1m', // Test duration
      preAllocatedVUs: 500, // Initial pool of virtual users
      maxVUs: 5000, // Maximum number of virtual users
    },
  },
};

export default function () {
  let res = http.get('http://load-testing-index.murmurations.network/v2/nodes?lat=51.493518&lon=0.009199&range=10km');
  
  // Check the response status
  let success = check(res, {
    'status is 200': (r) => r.status === 200,
  });

  // If the status is not 200, log an error message
  if (!success) {
    console.error(`Error: Expected status 200 but got ${res.status} - ${res.body}`);
  }
}
```

## 4. Run the Test

```bash
k6 run load-test.js
```

## 5. Check the Results

### Key Metrics

- **http_req_duration**: Provides a comprehensive view of response times. Aim for < 500 milliseconds.
- **http_req_failed**: Ensures request reliability. Aim for 0%.

**Comment by geoffturk** [comment]
The aim is to determine how many read (GET) and write (POST) requests an index can reliably handle without errors given its specific hardware (8VCPU, 16GB RAM - 19€/month Hetzner.cloud server).

## GET Assumptions

- http://load-testing-index.murmurations.network/v2/nodes
  - 50% of requests
- http://load-testing-index.murmurations.network/v2/nodes?page_size=100
  - 25% of requests
- http://load-testing-index.murmurations.network/v2/nodes?page_size=500
  - 15% of requests
- http://load-testing-index.murmurations.network/v2/nodes?page_size=1000
  - 10% of requests

## POST Assumptions

Use these sample profiles but with different profile_urls:

- https://test-tools.murmurations.network/profiles/clzd3cml2000009ld73u3haqk
  - 40% of requests
- https://test-tools.murmurations.network/profiles/clzd3h4be000009l5egvt7wwh
  - 30% of requests
- https://test-tools.murmurations.network/profiles/clzd3uer9000009mj5xmo4rqs
  - 30% of requests

**Comment by maxyzli** [comment]
Update:

The event processing speed will be the bottleneck of our system. Generally, MongoDB can handle around 1000 QPS without any issue. However, the challenge lies in the validation and updating of Elasticsearch, which currently manages about 25 write requests per second.

The 25 QPS rate is observed when k6 finishes and all the data is validated and stored in Elasticsearch.

**Comment by maxyzli** [comment]
@geoffturk 

Running Murmurations Services on an 8 VCPU, 16 GB RAM cloud server, with 5000 records in the database and 5 index services each with limits of 128Mi memory and 256m CPU, can handle read QPS of about 100 without any service hitting OOM or exceeding CPU limits.

There are many parameters we can adjust, such as the number of index services, their limits, and the number of records in the database.

**Comment by geoffturk** [comment]
https://github.com/MurmurationsNetwork/MurmurationsServices/blob/9346cd48271c41dcabf4faeb9c0cf573a76bf97b/test/load-testing/README.md#8-summary
