### ISSUE TITLE
Duplicate Indexing Requests

### ISSUE THREAD

**Issue by scyclops** [MurmurationsNetwork/MurmurationsServices#855]
I started submitting 10 request per second to the /nodes endpoint and it appears to have triggered an ongoing flood of duplicate requests to the profiles hosted on my server (trashnothing.com) from the following IPs: 78.47.72.119 and 167.235.140.151

Here is the URL of one profile that was requested hundreds of times in case that helps debug things: https://trashnothing.com/app/post/44344629/murmuration.json

I stopped submitting requests to the /nodes endpoint and started returning 404 errors for every profile request to my server to try to stop the flood of requests but neither of those things seems to have stopped the requests.  As far as I know, the requests are still coming in.  I've blocked them from my server at the Cloudflare level to prevent problems on my end.

**Comment by geoffturk** [comment]
Thanks for reporting this issue. We're looking into it now.

**Comment by geoffturk** [comment]
@scyclops Just to confirm I am understanding you correctly, are you saying that you submitted 10 requests per second, but each request was for different JSON profiles, all at unique URLs? 

IOW, if you had 6,000 unique JSON profile URLs, you sent each of them once in the course of 10 minutes?

**Comment by geoffturk** [comment]
OK, we've identified the probable cause and will fix it soon, but we want to run some tests first.

Out of curiosity, how many profiles do you want to post in total (you've posted just over 10,000 so far to the production index)? Also, how often do you expect to be updating them and roughly how many per update period?

**Comment by geoffturk** [comment]
I see the new profiles being posted to the production Index. It seems the problem has been resolved so I will close this issue.

If you ever have any questions, feel free to reach out again. FYI, we have a Telegram group for technical questions and issues.

https://t.me/+SS7GuP5kMDf-zx6l
